### ISSUE TITLE
Readiness probe fails when creating a Ray cluster supporting serve 

### ISSUE THREAD

**Issue by blublinsky** [ray-project/kuberay#1828] opened 2024-01-11 11:35 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I initially opened an issue https://github.com/ray-project/kuberay/issues/1826 about readiness probe, and was told that this is a feature. Unfortunately, this assumes that a ray cluster with serve support is already populated with the application, which might not be true. The following yaml is perfectly valid:
```
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  annotations:
    ray.io/enable-serve-service: "true"
  name: test-cluster
spec:
  headGroupSpec:
    rayStartParams:
      dashboard-agent-listen-port: "52365"
      dashboard-host: 0.0.0.0
      metrics-export-port: "8080"
    serviceType: ClusterIP
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.9.0-py310
            ports:
              - containerPort: 6379
                name: gcs
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8000
                name: serve
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: "2"
                memory: 4Gi
  workerGroupSpecs:
    - groupName: small-wg
      maxReplicas: 1
      minReplicas: 1
      replicas: 1
      rayStartParams:
        node-ip-address: $MY_POD_IP
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.9.0-py310
            lifecycle:
              preStop:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - ray stop
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: "2"
                memory: 4Gi
```
It creates a cluster with serve annotation without any applications. Readiness probe in this case is guaranteed to fail because port 8000 was not initialized yet

### Reproduction script

Use the above yaml

### Anything else

The current Readiness probe is designed to be not generic, but rather for a very specific use case where the cluster is immediately populated with applications. If this is not the case then
```
wget -T 2 -q -O- http://localhost:8000/-/healthz | grep success]
```
Is guaranteed to fail

I think the better option is not to enforce it in the general case, as it is done, but rather:
1. Remove it from the pod.go
2. Define the desired readiness probe explicitly in the rayservice_controller.go to overwrite the default

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Yicheng-Lu-llll** [comment] 2024-01-11 17:27
If there is no serve replica in the worker Pod, it will continue running but in an unready status. The readiness failure is expected, and we rely on this failure to remove the worker Pod's endpoint from the serve service (which is the only user-facing service).

You can still submit serve apps through the head service, as the head Pod does not use a readiness probe to check serve health.

**Comment by blublinsky** [comment] 2024-01-11 18:43
You are missing the point. Its an independent cluster created using RayCluster not RayServe. The cluster is never going to be ready, so if I am waiting for the cluster to be ready, its an infinite wait

**Comment by blublinsky** [comment] 2024-01-11 18:45
You are putting this readiness check in the assumption that the only way to create a ray cluster for serve is through the Ray Serve, which is not the case

**Comment by Yicheng-Lu-llll** [comment] 2024-01-11 20:33
Based on my current knowledge, an 'unready' status just means the Pod is not ready for serving traffic(which is true even you use Raycluster for serving). Are there any particular reasons why a Pod being in an unready status is not acceptable?

**Comment by blublinsky** [comment] 2024-01-11 21:03
@Yicheng-Lu-llll, An unhealthy pod means that the cluster is not created successfully. So if we are waiting for the cluster to be ready, as we do, we will wait forever, which is not acceptable.

**Comment by blublinsky** [comment] 2024-01-11 21:04
The other issue, as I said before, I saw Ray Serve never getting to the ready state either

**Comment by Yicheng-Lu-llll** [comment] 2024-01-11 22:55
I get your point! The issue is that the current Kuberay logic sets the RayCluster status to 'Ready' only if all Ray Pods are running and in a ready status which is not always true if check serve health check in readiness probe.

**Comment by Yicheng-Lu-llll** [comment] 2024-01-11 23:34
My current thinking is that we need clear definition of each RayService/Raycluster status.

**Comment by blublinsky** [comment] 2024-01-12 09:31
So can we do something in the meantime? This is blocking me

**Comment by blublinsky** [comment] 2024-01-12 18:28
Maybe you can in the interim remove 
```
wget -T 2 -q -O- http://localhost:8000/-/healthz | grep success]
```
from the readiness probe until you figure out a different approach

**Comment by blublinsky** [comment] 2024-01-17 11:00
@Yicheng-Lu-llll, @kevin85421 Did more testing of that new readiness probe, and here are my findings.
It relies on execution of the following command on every worker node:
```
wget -T 2 -q -O- http://localhost:8000/-/healthz | grep success]
```
According to the documentation here https://docs.ray.io/en/latest/serve/architecture.html
```
HTTP Proxy: By default, there is one HTTP proxy actor on the head node. This actor runs a [Uvicorn](https://www.uvicorn.org/) HTTP server that accepts incoming requests, forwards them to replicas, and responds once they are completed. For scalability and high availability, you can also run a proxy on each node in the cluster via the proxy_location field inside [serve.start()](https://docs.ray.io/en/latest/serve/api/index.html#core-apis) or [the config file](https://docs.ray.io/en/latest/serve/production-guide/config.html#serve-in-production-config-file).
``` 
When I am looking at configuration https://docs.ray.io/en/latest/serve/production-guide/config.html#serve-in-production-config-file
```
The proxy_location field configures where to run proxies to handle traffic to the cluster. You can set proxy_location to the following values:
- EveryNode (default): Run a proxy on every node in the cluster that has at least one replica actor.
- HeadOnly: Only run a single proxy on the head node.
- Disabled: Don’t run proxies at all. Set this value if you are only making calls to your applications using deployment handles.
```
Which basically means that the whole premiss is not guaranteed. As per this documentation, although `EveryNode` is the default setting, unless the amount of replicas is equal to the amount of nodes in the cluster, which might not be the case.  To make things even worse, in the case of autoscaling, the amount of replicas has to be equal to the max of the potential amount of nodes. 
Unless Ray Serve changes the code to create proxy on every node in the cluster regardless of the presence of a replica actor, the whole Ray Service implementation is extremely error prone.

**Comment by Yicheng-Lu-llll** [comment] 2024-01-21 00:14
Hi @blublinsky, if there is no replica in a Ray node, then causing it to fail the readiness probe to remove it from the serve service seems reasonable to me. Before moving the health check to the readiness probe, if you use a 'Ray cluster supporting serve', worker Pods would not be removed from the serve service even if they are unhealthy, as the health check happened in the Rayservice controller instead of the Raycluster controller. Therefore, moving it to the readiness probe actually improves High Availability.

By the way, currently, if you use a 'Ray cluster supporting serve' and the head Pod's proxy actor is dead, there is no mechanism to detect it, as far as I understand.

**Comment by Yicheng-Lu-llll** [comment] 2024-02-02 05:41
Hi @blublinsky, I would like to update the latest changes and the current behavior for "Ray cluster supporting serve".

1. To enable a "Ray cluster supporting serve", users need to manually add the· ray.io/enable-serve-service· annotation to the RayCluster CR.
2. The KubeRay operator will create a serve service for "Ray cluster supporting serve" and this serve service will, by default, select all the Ray nodes regardless. And the automatic injection of serve health checks has been removed.
3. To achieve high availability, users need to manually inject readiness probe or add any other mechanism they desire.

**Comment by blublinsky** [comment] 2024-02-02 08:30
Thank you @Yicheng-Lu-llll this is exactly what is done in https://github.com/ray-project/kuberay/pull/1728/files#diff-08cd009406904b1508453b7045827cd8cfd8615dd7e472a15eeb38edee72a0c0. in apiserver/pkg/util/cluster.go line 537

**Closed** 2024-02-02 18:36 UTC
Labels: bug, P2
