### ISSUE TITLE
[Feature] Support for generateName with RayJob

### ISSUE THREAD

**Issue by ashahab** [ray-project/kuberay#1622] opened 2023-11-03 00:15 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

RayJobs currently use K8s jobs to submit and track jobs. One of the features supported by k8s jobs is [generateName](https://github.com/kubernetes/kubernetes/issues/44501). 

However RayJobs do not support that even though it's part of the RayJob schema. Users have to figure out unique names for jobs that they launch multiple times. 
Operator-level support for generateName would allow users to specify the prefix of the job name, and have the job names automatically generated.

### Use case

As a user I want to launch multiple RayJobs with the same prefix.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment] 2023-11-03 17:57
Thanks for the feature request.  The use case makes sense, and I think adding this feature won't negatively affect other components.  cc @kevin85421 @hongchaodeng any concerns about this? If not, we welcome your PR!

**Comment by kevin85421** [comment] 2024-01-18 23:45
Add more context: Currently, we use the name of the RayJob custom resource as the name for the submitter Kubernetes Job to avoid creating multiple submitter Kubernetes Jobs caused by a stale informer cache. If we use `generteName`, we may need another way to avoid double creations.

cc @andrewsykim for additional input on how to avoid duplicate creations.

**Comment by andrewsykim** [comment] 2024-01-19 01:43
> Add more context: Currently, we use the name of the RayJob custom resource as the name for the submitter Kubernetes Job to avoid creating multiple submitter Kubernetes Jobs caused by a stale informer cache. If we use generteName, we may need another way to avoid double creations.

If I'm understanding correctly, we can still continue to use the name of RayJob for the submitter job name. The feature request is about being able to use generateName for the RayJob itself.

**Comment by kevin85421** [comment] 2024-01-19 02:03
@andrewsykim are you interested in this issue?

**Comment by andrewsykim** [comment] 2024-01-19 02:09
> Oops, I fully misunderstood the issue lol.

@kevin85421 actually I think I may have misunderstood the issue. 

Generate name already works for RayJobs today:
```
$ cat myrayjob.yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  generateName: rayjob-sample
spec:
...

$ kubectl create -f myrayjob.yaml 
rayjob.ray.io/rayjob-sampleh4r7r created
configmap/ray-job-code-sample created
```

@ashahab were you asking to support generateName for the RayJob or generateName in submitterPodTemplate?

**Comment by andrewsykim** [comment] 2024-01-30 22:51
@ashahab as far as I can tell, this is already supported so I'm inclined to close the issue. Can you confirm based on my last comment?

**Comment by kevin85421** [comment] 2024-02-03 08:45
This is already supported as Andrew mentioned. Close this issue.

**Closed by kevin85421** 2024-02-03 08:45 UTC
Labels: enhancement, rayjob
