### ISSUE TITLE
[Bug] rayjob CRD not getting reconciled by operator

### ISSUE THREAD

**Issue by btang-stripe** [ray-project/kuberay#1129] opened 2023-05-31 04:45 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Currently trying to test KubeRay with an existing EKS cluster but am having a hard time debugging issues with a RayJob not getting picked up by the operator when running `kubectl apply -f ray-operator/config/samples/ray_v1alpha1_rayjob.yaml`. Running `kubectl apply -f ray-operator/config/samples/ray-cluster.mini.yaml` does however spin up the pod for the cluster head.

Currently using v0.5.0 
kubectl 1.23.16
Kubernetes EKS 1.24.13

### Reproduction script

Installing the operator on an Amazon EKS cluster:
```
$ kubectl create -k ray-operator/config/default 
namespace/ray-system created
customresourcedefinition.apiextensions.k8s.io/rayclusters.ray.io created
customresourcedefinition.apiextensions.k8s.io/rayjobs.ray.io created
customresourcedefinition.apiextensions.k8s.io/rayservices.ray.io created
serviceaccount/kuberay-operator created
role.rbac.authorization.k8s.io/kuberay-operator-leader-election created
clusterrole.rbac.authorization.k8s.io/kuberay-operator created
rolebinding.rbac.authorization.k8s.io/kuberay-operator-leader-election created
clusterrolebinding.rbac.authorization.k8s.io/kuberay-operator created
service/kuberay-operator created
deployment.apps/kuberay-operator created
```

The pod starts up successfully:
```
$ kubectl get pods -nray-system
NAME                               READY   STATUS    RESTARTS   AGE
kuberay-operator-6cf5d9548-vzh6b   1/1     Running   0          2m6s
```

With the following logs:
```
$ kubectl logs -nray-system kuberay-operator-6cf5d9548-vzh6b
2023-05-31T04:32:56.189Z	INFO	setup	the operator	{"version:": ""}
2023-05-31T04:32:56.493Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2023-05-31T04:32:56.493Z	INFO	setup	starting manager
2023-05-31T04:32:56.493Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2023-05-31T04:32:56.493Z	INFO	controller-runtime.manager.controller.raycluster-controller	Starting EventSource	{"reconciler group": "ray.io", "reconciler kind": "RayCluster", "source": "kind source: /, Kind="}
2023-05-31T04:32:56.794Z	INFO	controller-runtime.manager.controller.raycluster-controller	Starting EventSource	{"reconciler group": "ray.io", "reconciler kind": "RayCluster", "source": "kind source: /, Kind="}
2023-05-31T04:32:56.894Z	INFO	controller-runtime.manager.controller.raycluster-controller	Starting EventSource	{"reconciler group": "ray.io", "reconciler kind": "RayCluster", "source": "kind source: /, Kind="}
2023-05-31T04:32:56.994Z	INFO	controller-runtime.manager.controller.raycluster-controller	Starting Controller	{"reconciler group": "ray.io", "reconciler kind": "RayCluster"}
2023-05-31T04:32:56.994Z	INFO	controller-runtime.manager.controller.raycluster-controller	Starting workers	{"reconciler group": "ray.io", "reconciler kind": "RayCluster", "worker count": 1}
```

The rayjob is created successfully:
```
$ kubectl apply -f ray-operator/config/samples/ray_v1alpha1_rayjob.yaml
rayjob.ray.io/rayjob-sample created
configmap/ray-job-code-sample created
$ kubectl get rayjob
NAME            AGE
rayjob-sample   7s
```

But the pods for the head/workers never get created:
```
$ kubectl get pods -A
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
kube-system   aws-node-czr5r                         1/1     Running   0          10h
kube-system   aws-node-mp8mn                         1/1     Running   0          10h
kube-system   coredns-6959659697-cjfn6               1/1     Running   0          10h
kube-system   kube-proxy-bqjdh                       1/1     Running   0          10h
kube-system   kube-proxy-c5d4l                       1/1     Running   0          10h
ray-system    kuberay-operator-6cf5d9548-vzh6b       1/1     Running   0          4m42s
```

There are no additional log events from the operator

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by arihantsurana** [comment] 2023-10-30 07:59
I am facing a similar issue with Kuberay on a namespace install.
I faced this issue after I upgraded from Kuberay v0.5.0 to v1.0.0-rc.1
I can also see the following error in my logs:
```
2023-10-30T07:32:07.020Z	INFO	controllers.RayService	Reconciling the cluster component.	{"ServiceName": "<my namespace>/<my serve resource name>"}
2023-10-30T07:32:07.020Z	DEBUG	controllers.RayService	reconcileRayCluster	{"delete Ray cluster": "<my serve resource name>-raycluster-9hxh9", "reason": "Deletion timestamp 2023-10-30 07:19:35.381769854 +0000 UTC m=+143.794313515 for RayCluster <my serve resource name>-raycluster-9hxh9 has passed. Deleting cluster immediately."}
2023-10-30T07:32:07.037Z	DEBUG	controllers.RayService	reconcileRayCluster	{"delete Ray cluster": "<my serve resource name>-raycluster-9sjjw", "reason": "Deletion timestamp 2023-10-30 07:19:35.381777255 +0000 UTC m=+143.794320913 for RayCluster sampling-raycluster-9sjjw has passed. Deleting cluster immediately."}
2023-10-30T07:32:07.058Z	DEBUG	controllers.RayService	reconcileRayCluster	{"delete Ray cluster": "<my serve resource name>-raycluster-tcmfr", "reason": "Deletion timestamp 2023-10-30 07:19:35.381745356 +0000 UTC m=+143.794289023 for RayCluster <my serve resource name>-raycluster-tcmfr has passed. Deleting cluster immediately."}
2023-10-30T07:32:07.076Z	ERROR	controllers.RayService	Failed to check if head pod is running and ready!	{"ServiceName": "<my namespace>/<my serve resource name>", "error": "Found 0 head pods for RayCluster <my serve resource name>-raycluster-jhknj in the namespace aims-qa"}
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayServiceReconciler).Reconcile
	/workspace/controllers/ray/rayservice_controller.go:168
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
2023-10-30T07:32:07.076Z	ERROR	controllers.RayService	Fail to reconcileServe.	{"ServiceName": "<my namespace>/<my serve resource name>", "error": "Found 0 head pods for RayCluster <my serve resource name>-raycluster-jhknj in the namespace <my namespace>"}
```

**Comment by kevin85421** [comment] 2023-12-27 07:26
@arihantsurana, have you solved the question or do you have a reproduction script? I can't reproduce this issue on my local Kind cluster by running the following commands:

```sh
# Path: kuberay/
kubectl create -k ray-operator/config/default
# Path: kuberay/ray-operator/config/samples
kubectl apply -f ray_v1alpha1_rayjob.yaml
```

Thanks!

**Comment by kevin85421** [comment] 2024-01-26 03:07
Close this issue. Feel free to reopen the issue if this still exists.

**Closed by kevin85421** 2024-01-26 03:07 UTC
Labels: bug, rayjob
