### ISSUE TITLE
(SOLVED) [Bug] Services don't spin up when using custom image

### ISSUE THREAD

**Issue by Addyvan** [ray-project/kuberay#198] opened 2022-03-16 18:38 UTC
## [MY SOLUTION]

I hadn't installed ray correctly, the head pod requires:
```
pip install "ray[default]"
```

### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

ray fails out when there is a python mismatch so I can't use the pre-built `rayproject/ray:latest`

Everything works fine if I use the default images, the head shows the following output:
```bash
$ k logs test-cluster-head-8lfdh
2022-03-16 11:28:26,008 INFO services.py:1414 -- View the Ray dashboard at http://10.244.14.70:8265
2022-03-16 11:28:23,886 INFO scripts.py:600 -- Local node IP: 10.244.14.70
2022-03-16 11:28:26,348 SUCC scripts.py:640 -- --------------------
2022-03-16 11:28:26,348 SUCC scripts.py:641 -- Ray runtime started.
2022-03-16 11:28:26,348 SUCC scripts.py:642 -- --------------------
2022-03-16 11:28:26,349 INFO scripts.py:644 -- Next steps
2022-03-16 11:28:26,349 INFO scripts.py:646 -- To connect to this Ray runtime from another node, run
2022-03-16 11:28:26,349 INFO scripts.py:652 --   ray start --address='10.244.14.70:6379' --redis-password='LetMeInRay'
2022-03-16 11:28:26,349 INFO scripts.py:654 -- Alternatively, use the following Python code:
2022-03-16 11:28:26,349 INFO scripts.py:656 -- import ray
2022-03-16 11:28:26,350 INFO scripts.py:668 -- ray.init(address='auto', _redis_password='LetMeInRay', _node_ip_address='10.244.14.70')
2022-03-16 11:28:26,350 INFO scripts.py:670 -- To connect to this Ray runtime from outside of the cluster, for example to
2022-03-16 11:28:26,350 INFO scripts.py:672 -- connect to a remote cluster from your laptop directly, use the following
2022-03-16 11:28:26,350 INFO scripts.py:674 -- Python code:
2022-03-16 11:28:26,350 INFO scripts.py:676 -- import ray
2022-03-16 11:28:26,350 INFO scripts.py:679 -- ray.init(address='ray://<head_node_ip_address>:10001')
2022-03-16 11:28:26,350 INFO scripts.py:683 -- If connection fails, check your firewall settings and network configuration.
2022-03-16 11:28:26,350 INFO scripts.py:687 -- To terminate the Ray runtime, run
2022-03-16 11:28:26,350 INFO scripts.py:688 --   ray stop
2022-03-16 11:28:26,351 INFO scripts.py:761 -- --block
2022-03-16 11:28:26,351 INFO scripts.py:763 -- This command will now block until terminated by a signal.
2022-03-16 11:28:26,351 INFO scripts.py:765 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly.
```

When using this spinoff container, or any other container with ray installed:
```Dockerfile
FROM rayproject/ray:latest

RUN conda install python=3.8.10
RUN pip install ray # I'm not sure why this is required honestly but otherwise ray is missing?
```
I get:
```
$ k logs test-cluster-head-ggrsn 
2022-03-16 11:25:58,569 INFO scripts.py:600 -- Local node IP: 10.244.14.69
2022-03-16 11:25:59,945 SUCC scripts.py:640 -- --------------------
2022-03-16 11:25:59,945 SUCC scripts.py:641 -- Ray runtime started.
2022-03-16 11:25:59,945 SUCC scripts.py:642 -- --------------------
2022-03-16 11:25:59,945 INFO scripts.py:644 -- Next steps
2022-03-16 11:25:59,946 INFO scripts.py:645 -- To connect to this Ray runtime from another node, run
2022-03-16 11:25:59,946 INFO scripts.py:649 --   ray start --address='10.244.14.69:6379' --redis-password='LetMeInRay'
2022-03-16 11:25:59,946 INFO scripts.py:654 -- Alternatively, use the following Python code:
2022-03-16 11:25:59,946 INFO scripts.py:656 -- import ray
2022-03-16 11:25:59,946 INFO scripts.py:660 -- ray.init(address='auto', _redis_password='LetMeInRay', _node_ip_address='10.244.14.69')
2022-03-16 11:25:59,946 INFO scripts.py:670 -- To connect to this Ray runtime from outside of the cluster, for example to
2022-03-16 11:25:59,946 INFO scripts.py:672 -- connect to a remote cluster from your laptop directly, use the following
2022-03-16 11:25:59,946 INFO scripts.py:674 -- Python code:
2022-03-16 11:25:59,946 INFO scripts.py:676 -- import ray
2022-03-16 11:25:59,946 INFO scripts.py:677 -- ray.init(address='ray://<head_node_ip_address>:10001')
2022-03-16 11:25:59,946 INFO scripts.py:682 -- If connection fails, check your firewall settings and network configuration.
2022-03-16 11:25:59,946 INFO scripts.py:687 -- To terminate the Ray runtime, run
2022-03-16 11:25:59,946 INFO scripts.py:688 --   ray stop
2022-03-16 11:25:59,946 INFO scripts.py:761 -- --block
2022-03-16 11:25:59,947 INFO scripts.py:762 -- This command will now block until terminated by a signal.
2022-03-16 11:25:59,947 INFO scripts.py:764 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly.
```

The kopf based operator works find with custom images for context. 

### Reproduction script

```yaml
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: test-cluster
spec:
  headGroupSpec:
    serviceType: NodePort
    enableIngress: true
    rayStartParams:
      block: "true"
      dashboard-host: "0.0.0.0"
      node-ip-address: "$MY_POD_IP"
      num-cpus: "3"
      port: "6379"
      redis-password: "LetMeInRay"
    replicas: 1
    template:
      spec:
        containers:
          - name: ray-head
            image: <CUSTOM-IMAGE>
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 3000m
              requests:
                cpu: 3000m
            env:
            - name: TYPE
              value: head
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
        volumes:
        - emptyDir: {}
          name: log-volume
      metadata:
        labels:
          groupName: headgroup
          rayNodeType: head
          rayCluster: test-cluster

  workerGroupSpecs:
  - rayStartParams:
      block: "true"
      node-ip-address: "$MY_POD_IP"
      redis-password: "LetMeInRay"
    replicas: 4
    minReplicas: 4
    maxReplicas: 4
    groupName: workergroup
    template:
      spec:
        initContainers:
          - name: init-myservice
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        containers:
          - name: ray-worker
            image: <CUSTOM-IMAGE>
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 4000m
              requests:
                cpu: 4000m
            volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
            env:
            - name: TYPE
              value: worker
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RAY_DISABLE_DOCKER_CPU_WARNING
              value: "1"
            - name: CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: ray-worker
                  resource: requests.cpu
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
        volumes:
        - emptyDir: {}
          name: log-volume
      metadata:
        annotations:
          key: value
        labels:
          rayNodeType: worker
          groupName: workergroup
          rayCluster: test-cluster
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment] 2022-12-10 08:06
The issue is labeled as solved. Close it. Thank @Addyvan!

**Closed by kevin85421** 2022-12-10 08:06 UTC
Labels: bug
