### ISSUE TITLE
[Bug] Quickstart example is not working.

### ISSUE THREAD

**Issue by goswamig** [ray-project/kuberay#283] opened 2022-06-02 07:55 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

At first it appears to be more like Ray issue but nevertheless its a part of [kuberay](https://docs.ray.io/en/latest/cluster/kuberay.html) and [k8s](https://docs.ray.io/en/latest/cluster/kubernetes.html) documentation  

I've followed [kuberay](https://docs.ray.io/en/latest/cluster/kuberay.html) doc and was able to use autoscaler which added more worker successfully. 
```
NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE
default       raycluster-complete-head-xc9pg                 2/2     Running   0          13m
default       raycluster-complete-worker-small-group-fvfn4   1/1     Running   0          10m
default       raycluster-complete-worker-small-group-g9bk5   1/1     Running   0          10m
default       raycluster-complete-worker-small-group-jzjs4   1/1     Running   0          14m
```

Operator
```
ray-system    kuberay-operator-74455ff8c6-5qdrx              1/1     Running   0          26m

```
surprisingly there was nothing for autoscaling, was this expected? 

I was able to successfully do port-forward for head node service for `dashboard :8265` and `ray client server port: 10001`   

After this since there wasn't any working example from kuberay, I tried to use [k8s](https://docs.ray.io/en/latest/cluster/kubernetes.html) documentation to run some program.

I started with [Running Ray programs with Ray Jobs Submission](https://docs.ray.io/en/latest/cluster/kubernetes.html#running-ray-programs-with-ray-jobs-submission) with sample [script.py ](https://docs.ray.io/en/latest/cluster/job-submission.html#jobs-overview)

this resultant into following error.

```
$ ray job submit --runtime-env-json='{"working_dir": "./", "pip": ["requests==2.26.0"]}' -- "python script.py"
Job submission server address: http://127.0.0.1:8265
2022-06-02 00:34:53,279    ERROR packaging.py:84 -- Issue with path: /Users/gauta/.docker/run/docker-cli-api.sock
Traceback (most recent call last):
  File "/usr/local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/ray/scripts/scripts.py", line 1958, in main
    return cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ray/dashboard/modules/job/cli.py", line 151, in job_submit
    job_id = client.submit_job(
  File "/usr/local/lib/python3.9/site-packages/ray/dashboard/modules/job/sdk.py", line 255, in submit_job
    self._upload_working_dir_if_needed(runtime_env)
  File "/usr/local/lib/python3.9/site-packages/ray/dashboard/modules/job/sdk.py", line 232, in _upload_working_dir_if_needed
    package_uri = self._upload_package_if_needed(
  File "/usr/local/lib/python3.9/site-packages/ray/dashboard/modules/job/sdk.py", line 211, in _upload_package_if_needed
    package_uri = get_uri_for_directory(package_path, excludes=excludes)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 333, in get_uri_for_directory
    hash_val = _hash_directory(directory, directory,
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 121, in _hash_directory
    _dir_travel(root, excludes, handler, logger=logger)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 88, in _dir_travel
    _dir_travel(sub_path, excludes, handler, logger=logger)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 88, in _dir_travel
    _dir_travel(sub_path, excludes, handler, logger=logger)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 88, in _dir_travel
    _dir_travel(sub_path, excludes, handler, logger=logger)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 85, in _dir_travel
    raise e
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 82, in _dir_travel
    handler(path)
  File "/usr/local/lib/python3.9/site-packages/ray/_private/runtime_env/packaging.py", line 112, in handler
    with path.open("rb") as f:
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 102] Operation not supported on socket: '/Users/gauta/.docker/run/docker-cli-api.sock'
```

Then I tried with 
[Using Ray Client to connect from within the Kubernetes cluster](https://docs.ray.io/en/latest/cluster/kubernetes.html#using-ray-client-to-connect-from-within-the-kubernetes-cluster)

However this also resulted in following error
```
$ python3 ray/doc/kubernetes/example_scripts/run_local_example.py 
Traceback (most recent call last):
  File "/Users/gauta/ray/doc/kubernetes/example_scripts/run_local_example.py", line 60, in <module>
    ray.init(f"ray://127.0.0.1:{LOCAL_PORT}")
  File "/usr/local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ray/worker.py", line 800, in init
    return builder.connect()
  File "/usr/local/lib/python3.9/site-packages/ray/client_builder.py", line 151, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/usr/local/lib/python3.9/site-packages/ray/util/client_connect.py", line 33, in connect
    conn = ray.connect(
  File "/usr/local/lib/python3.9/site-packages/ray/util/client/__init__.py", line 228, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/usr/local/lib/python3.9/site-packages/ray/util/client/__init__.py", line 88, in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
  File "/usr/local/lib/python3.9/site-packages/ray/util/client/worker.py", line 697, in _server_init
    raise ConnectionAbortedError(
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 649, in Datapath
    modified_init_req, job_config = prepare_runtime_init_req(init_req)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 571, in prepare_runtime_init_req
    job_config = pickle.loads(req.job_config)
AttributeError: Can't get attribute 'ParsedRuntimeEnv' on <module 'ray._private.runtime_env.validation' from '/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/runtime_env/validation.py'>
```

any help would be appreciated. 

### Reproduction script

Provided details in above section. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment] 2022-06-02 15:52
> surprisingly there was nothing for autoscaling, was this expected?

The autoscaler for each Ray cluster is attached as a sidecar to Ray head pod, the output of `kubectl get pod <ray-head>` will show two containers and `kubectl get pod <ray-head> -o yaml` will show the full details of the pod.

I will follow up soon to help address the problems encountered.

**Comment by DmitriGekhtman** [comment] 2022-06-02 17:26
> Then I tried with
[Using Ray Client to connect from within the Kubernetes cluster](https://docs.ray.io/en/latest/cluster/kubernetes.html#using-ray-client-to-connect-from-within-the-kubernetes-cluster)
However this also resulted in following error

The good news is that the connection was successfully established!
The bad news is that Ray client is extremely sensitive to Ray version mismatch. Ray versions on client and server side must align exactly. I suspect there might be a mismatch in your situation.

**Comment by architkulkarni** [comment] 2022-06-02 19:47
Thanks for finding the root cause, this is an interesting edge case... We `.open()` the files so that we can read the contents and hash them.  We use the hash to prevent reuploading the working_dir when it's already been uploaded.

I think you're right that the solution is to skip over files that raise an exception when `.open()` is called.

**Comment by goswamig** [comment] 2022-06-02 22:54
@DmitriGekhtman Thanks for help, I tried with empty directory and fixed my client ray version matching with ray version in my ray cluster. I hit into another issue

```
$ ray job submit --runtime-env-json='{"working_dir": "./", "pip": ["requests==2.26.0"]}' -- "python script.py"
Job submission server address: http://127.0.0.1:8265
2022-06-02 15:52:09,000	INFO dashboard_sdk.py:264 -- Uploading package gcs://_ray_pkg_e8207fca9ff3cfb8.zip.
2022-06-02 15:52:09,001	INFO packaging.py:388 -- Creating a file package for local directory './'.

-------------------------------------------------------
Job 'raysubmit_GYsi1hKWcARZdR1T' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_GYsi1hKWcARZdR1T
  Query the status of the job:
    ray job status raysubmit_GYsi1hKWcARZdR1T
  Request the job to be stopped:
    ray job stop raysubmit_GYsi1hKWcARZdR1T

Tailing logs until the job exits (disable with --no-wait):

---------------------------------------
Job 'raysubmit_GYsi1hKWcARZdR1T' failed
---------------------------------------

Status message: runtime_env setup failed: Failed to setup runtime environment.
Could not create the actor because its associated runtime env failed to be created.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 281, in CreateRuntimeEnv
    runtime_env_setup_task, timeout=setup_timeout_seconds
  File "/home/ray/anaconda3/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 151, in _setup_runtime_env
    uri, runtime_env, context, logger=per_job_logger
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/runtime_env/working_dir.py", line 150, in create
    return await loop.run_in_executor(None, _create)
  File "/home/ray/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/runtime_env/working_dir.py", line 145, in _create
    uri, self._resources_dir, logger=logger
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/runtime_env/packaging.py", line 480, in download_and_unpack_package
    raise IOError(f"Failed to fetch URI {pkg_uri} from GCS.")
OSError: Failed to fetch URI gcs://_ray_pkg_e8207fca9ff3cfb8.zip from GCS.
```

**Comment by DmitriGekhtman** [comment] 2022-06-02 23:02
That's interesting. cc @architkulkarni again
We'll try to reproduce this -- Could you link to the configs you used to deploy?
Also what does your local environment look like (OS, Ray version, Python version).

**Comment by architkulkarni** [comment] 2022-06-02 23:24
The URI issue might be the same as this one: https://github.com/ray-project/ray/issues/23423

According to the reports on that issue, if you change the contents of the working_dir in some way (e.g. by adding a file or editing a file), it's likely to go away--can you let us know if that works?  The issue should be fixed in the nightly wheels, if you're willing to try them out (installing them both on your local machine and on the cluster).

**Comment by goswamig** [comment] 2022-06-03 00:10
local:
OS: Mac monterey 12.3
Python 3.9.7
ray version local and remote: 1.12.0 

I've used [kuberay doc ](https://docs.ray.io/en/latest/cluster/kuberay.html)to deploy it as mentioned in the instruction.


Sure I can try nightly wheel. Did you mean `working_dir` from command if so then Ray cluster will not be able to find the script.py right?

Did you mean some other `working_dir` ?

```
$ ray job submit --runtime-env-json='{"pip": ["requests==2.26.0"]}' -- "python script.py"
Job submission server address: http://127.0.0.1:8265

-------------------------------------------------------
Job 'raysubmit_QXaSjqdZrNX3Yrcz' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_QXaSjqdZrNX3Yrcz
  Query the status of the job:
    ray job status raysubmit_QXaSjqdZrNX3Yrcz
  Request the job to be stopped:
    ray job stop raysubmit_QXaSjqdZrNX3Yrcz

Tailing logs until the job exits (disable with --no-wait):
/bin/sh: 1: python script.py: not found

---------------------------------------
Job 'raysubmit_QXaSjqdZrNX3Yrcz' failed
---------------------------------------

Status message: Job failed due to an application error, last available logs:
/bin/sh: 1: python script.py: not found
```

**Comment by goswamig** [comment] 2022-06-03 00:44
I noticed my local py is 3.9.9 and remote ray cluster is on py 3.7.7. Do u think that could be reason?

**Comment by DmitriGekhtman** [comment] 2022-06-03 04:30
Yeah, I should have mentioned above: Python minor versions must match as well for Ray client.

**Comment by DmitriGekhtman** [comment] 2022-06-03 04:31
> Did you mean working_dir from command if so then Ray cluster will not be able to find the script.py right?

I'm confused about this point too.

**Comment by goswamig** [comment] 2022-06-03 06:21
@architkulkarni ^ am I missing something on working_dir?

**Comment by architkulkarni** [comment] 2022-06-03 16:48
Sorry you're absolutely right about working_dir, it's required for the
script file to be on the cluster. In that case could you try one of the
other workarounds? (edit the working_dir contents or use nightly wheel on
local machine and cluster)

If you use the nightly, to be safe you can check that the Ray commit agrees
on the local machine and cluster; you can do this with `ray. __commit__` in
Python.

**Comment by goswamig** [comment] 2022-06-06 05:27
I already tried with adding/editing a file in `working_dir` which had `script.py` but it did not work. I will give a shot on nightly binary.

**Comment by goswamig** [comment] 2022-06-06 20:42
@architkulkarni Am i missing something.

```
$ ray job submit --runtime-env-json='{"working_dir": "/Users/gauta/testkuberay", "pip": ["requests==2.26.0"]}' -- "python script.py"
Job submission server address: http://127.0.0.1:8265
2022-06-06 13:39:56,276	INFO dashboard_sdk.py:264 -- Uploading package gcs://_ray_pkg_c1732e880f4c8b1e.zip.
2022-06-06 13:39:56,277	INFO packaging.py:388 -- Creating a file package for local directory '/Users/gauta/testkuberay'.

-------------------------------------------------------
Job 'raysubmit_FSUxQwtMeBX3fEmr' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_FSUxQwtMeBX3fEmr
  Query the status of the job:
    ray job status raysubmit_FSUxQwtMeBX3fEmr
  Request the job to be stopped:
    ray job stop raysubmit_FSUxQwtMeBX3fEmr

Tailing logs until the job exits (disable with --no-wait):
/bin/sh: 1: python script.py: not found

---------------------------------------
Job 'raysubmit_FSUxQwtMeBX3fEmr' failed
---------------------------------------

Status message: Job failed due to an application error, last available logs:
/bin/sh: 1: python script.py: not found

```

I already have file 
```
$ ls -lhrt /Users/gauta/testkuberay/
total 32
-rw-r--r--  1 gauta  staff    10K Jun  6 13:13 ray-cluster-complete.yaml
-rw-r--r--  1 gauta  staff   391B Jun  6 13:13 script.py
```

**Comment by architkulkarni** [comment] 2022-06-06 21:18
Ah sorry, you need to remove the quotes from "python script.py". Can you
try it again with this change?

**Comment by goswamig** [comment] 2022-06-06 21:55
thanks I was able to run both options using `ray submit` and connecting to raycluster. 

Feel free to close this issue. Thanks @architkulkarni  and @DmitriGekhtman  for help. 

I've also created a small PR https://github.com/ray-project/ray/compare/master...goswamig:patch-1

**Closed** 2022-06-06 22:00 UTC
Labels: bug

**Comment by architkulkarni** [comment] 2022-06-06 22:02
Thanks, good catch! That commit looks good, feel free to tag me on the pull request (it looks like the PR hasn't been created yet)
