### ISSUE TITLE
[Bug] [RayJob] First job pod sometimes fails to connect to Ray cluster

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1381] opened 2023-08-31 20:35 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Sometimes after submitting a `RayJob`, we see that the first job submission pod has failed:

```text
NAME                                        READY   STATUS      RESTARTS   AGE
kuberay-operator-7447d85d58-89nhg           1/1     Running     0          5m44s
rayjob-sample-hwbgg                         0/1     Error       0          2m55s
rayjob-sample-raycluster-vkbxr-head-4pnd5   1/1     Running     0          5m12s
rayjob-sample-w5nvf                         0/1     Completed   0          2m48s
```

In the logs for the errored pod, we see

```
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 248, in _check_connection_and_version
    self._check_connection_and_version_with_url(min_version, version_error_message)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 278, in _check_connection_and_version_with_url
    raise ConnectionError(
ConnectionError: Failed to connect to Ray at address: http://rayjob-sample-raycluster-vkbxr-head-svc.default.svc.cluster.local:8265.
```

The pod gets retried, so the RayJob itself eventually succeeds, but this is still unexpected because the RayJob controller is supposed to wait for the cluster to be ready before submitting the job.

### Reproduction script

`kubectl apply -f config/samples/ray_v1alpha1_rayjob.yaml`

### Anything else
[logs.zip](https://github.com/ray-project/kuberay/files/12490160/logs.zip)

It only happens sometimes.  (5-20% of the time?)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rueian** [comment] 2023-09-13 14:55
Hi @architkulkarni, @kevin85421

Is anyone working on this? If not, I would like to work on this.

## Investigation

Given the message from the [logs.zip](https://github.com/ray-project/kuberay/files/12490160/logs.zip):
```
Max retries exceeded with url: /api/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f063be65ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
It seems that the cause was the dashboard server didn't start yet.

## Solutions

I believe this issue can be addressed by sending an HTTP request to the dashboard server at line 209 of the below section. 

https://github.com/ray-project/kuberay/blob/36f32ed39ac5ef102e0310fa90a44e7b672b96c7/ray-operator/controllers/ray/rayjob_controller.go#L203-L215

If that request fails, we then requeue the reconciliation request by doing the same action when `rayClusterInstance.Status.State != rayv1alpha1.Ready`:

```go
err = r.updateState(ctx, rayJobInstance, nil, rayJobInstance.Status.JobStatus, rayv1alpha1.JobDeploymentStatusInitializing, nil)
return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
```

Or setting the job status to `rayv1alpha1.JobDeploymentStatusWaitForDashboard` and requeuing:

```go
err = r.updateState(ctx, rayJobInstance, nil, rayJobInstance.Status.JobStatus, rayv1alpha1.JobDeploymentStatusWaitForDashboard, nil)
return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
```

Would these be preferable solutions? By doing so, we can make sure that the dashboard server is ready before creating the k8s Job instance.

**Comment by architkulkarni** [comment] 2023-09-13 16:52
That sounds reasonable to me, and it would be great if you could submit a PR.  @kevin85421 what do you think of the approach? Originally we wanted to get rid of the dashboard HTTP client for job submission, but here the dashboard HTTP client is just being used to check that the dashboard is ready, which seems fine.

**Comment by kevin85421** [comment] 2023-09-15 06:00
It is OK as a workaround because we want to implement this fix before the release of KubeRay 1.0.0.

I am not a fan of this solution. In Kubernetes' convention, "ready" signifies that the resource is ready to serve traffic. Unfortunately, the "ready" state in RayCluster doesn't accurately reflect this, necessitating the use of an HTTP client to check the head Pod's status. For a long-term solution, I am contemplating revising the definition of "ready" in RayCluster by updating certain functions and probes.

In addition, we may consider creating the Kubernetes Job after the RayCluster is ready. If we can create the Job earlier, it can start some processes earlier, such as pulling images. Hence, we may also need to consider adding a waiting mechanism for the Job.

I will sync with @rueian offline to discuss possible solutions.

**Comment by architkulkarni** [comment] 2023-09-15 16:57
Great points, thanks for the discussion.  By the way, any ideas why the job submitter pod gets retried here? The pod has `RestartPolicyNever` so I'm a bit confused.

**Comment by kevin85421** [comment] 2023-09-16 08:14
> any ideas why the job submitter pod gets retried here?

We can have two-levels of retry:

* Connection: If the `ray job submit` command cannot establish a connection with the RayCluster, it shouldn't immediately fail. Instead, it should attempt to retry the connection. We could establish a timeout period, after which the `ray job submit` process will fail if a connection cannot be established. It is better to add some flags in the Ray Job Submission component.

* Application: If the `ray job submit` fails after the connection with the RayCluster has been established, the K8s Job Pod should fail and the Kubernetes Job will create a new Job Pod until the number of failures is higher than the backoff limit.

**Comment by kevin85421** [comment] 2023-12-24 06:12
Close with #1733

**Closed by kevin85421** 2023-12-24 06:12 UTC
Labels: bug, P1, rayjob
