### ISSUE TITLE
[Bug] make kustomize command is broken in the Ray operator

### ISSUE THREAD

**Issue by blublinsky** [ray-project/kuberay#1357] opened 2023-08-22 15:04 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Running `make kustomize` command produces an error. Additionally It tries to download `kustomize/v3@v3.10.0` which is 4 years old. 

### Reproduction script

Running 
```
make kustomize
```
Produces the following result:
```
test -s /Users/boris/Projects/kuberay/ray-operator/bin/kustomize ||  GOBIN=/Users/boris/Projects/kuberay/ray-operator/bin/kustomize/.. go install sigs.k8s.io/kustomize/kustomize/v3@v3.10.0
go: sigs.k8s.io/kustomize/kustomize/v3@v3.10.0 (in sigs.k8s.io/kustomize/kustomize/v3@v3.10.0):
        The go.mod file for the module providing named packages contains one or
        more exclude directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
make: *** [kustomize] Error 1
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shubhscoder** [comment] 2023-08-29 17:52
I realized that https://github.com/ray-project/kuberay/issues/1368 is a duplicate of this one.

**Closed** 2023-08-31 08:11 UTC
Labels: bug
