### ISSUE TITLE
[Bug]  Error "rayservices.ray.io" is invalid: metadata.annotations: Too long. when installing Ray Operator CRD

### ISSUE THREAD

**Issue by nilyin** [ray-project/kuberay#504] opened 2022-08-24 14:44 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When installing CRD object with command below:

`kubectl apply -k "github.com/ray-project/kuberay/ray-operator/config/crd?ref=v0.3.0"`

I have got:

`Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "rayservices.ray.io", Namespace: ""
for: "github.com/ray-project/kuberay/ray-operator/config/crd?ref=v0.3.0": CustomResourceDefinition.apiextensions.k8s.io "rayservices.ray.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

### Reproduction script

my configuration is as follows:

`
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment] 2022-08-24 17:18
This is a known issue -- you must `kubectl create` the CRD, not `kubectl apply`.
Closing as a duplicate of https://github.com/ray-project/kuberay/issues/271.

**Closed by DmitriGekhtman** 2022-08-24 17:18 UTC
Labels: bug

**Comment by nilyin** [comment] 2022-08-25 09:14
I see, thanks a lot. I was using Helm install guide for github readme page: 
https://github.com/ray-project/kuberay/tree/master/helm-chart/kuberay-operator)

please correct the page with the command description.

**Comment by DmitriGekhtman** [comment] 2022-08-25 14:51
PR to update the helm readme: https://github.com/ray-project/kuberay/pull/505
