### ISSUE TITLE
[Bug] rayjob worker could not start and the worker report `ValueError: Malformed address: `

### ISSUE THREAD

**Issue by slow-zhang** [ray-project/kuberay#923] opened 2023-02-22 07:48 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Hi team, i follow the guide https://ray-project.github.io/kuberay/ to create a rayjob use the example yaml as the doc, 

but the worker could not start, and the rayjob keep in created status:
```
tatus:
  Dashboard URL:          rayjob-sample-raycluster-fwj5h-head-svc.default.svc.cluster.local:8265
  Job Deployment Status:  Initializing
  Job Id:                 rayjob-sample-knr5g
  Ray Cluster Name:       rayjob-sample-raycluster-fwj5h
  Ray Cluster Status:
    Head:
Events:
  Type    Reason   Age   From               Message
  ----    ------   ----  ----               -------
  Normal  Created  11m   rayjob-controller  Created cluster rayjob-sample-raycluster-fwj5h
```

the below is the worker log

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 2596, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 588, in start
    node_ip_address = services.resolve_ip_for_localhost(node_ip_address)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 531, in resolve_ip_for_localhost
    raise ValueError(f"Malformed address: {address}")
ValueError: Malformed address: 
```

### Reproduction script

k apply -f ray_v1alpha1_rayjob.yaml

### Anything else

this is very strange the [code](https://github.com/ray-project/ray/blob/master/python/ray/scripts/scripts.py#L581) around services.resolve_ip_for_localhost checked it is not none but seem the [serveice](https://github.com/ray-project/ray/blob/master/python/ray/_private/services.py#L584).py go none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scottsun94** [comment] 2023-02-22 20:53
cc: @kevin85421 @architkulkarni

**Comment by slow-zhang** [comment] 2023-02-22 20:53
***@***.***：377636000地址：浙江省杭州市西湖区浙江大学西溪校区

**Comment by kevin85421** [comment] 2023-03-07 00:02
It appears that this issue may be a duplicate of https://github.com/ray-project/kuberay/issues/805. @slow-zhang would you mind trying the up-to-date master branch?

**Comment by kevin85421** [comment] 2023-04-11 21:53
This issue seems to be a duplicate of #805. Close this issue. Feel free to reopen this issue if you still observe this issue.

**Closed by kevin85421** 2023-04-11 21:53 UTC
Labels: bug, rayjob
