### ISSUE TITLE
RayController updating RayService resource every second.

### ISSUE THREAD

**Issue by msumitjain** [ray-project/kuberay#1044] opened 2023-04-24 20:52 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others / RayControllers, RayService

### What happened + What you expected to happen

We are using ArgoCD for deploying the RayService. We are observing a pulsing animation on the ArgoCD UI on RayService which indicates that Resource has been modified. It seems that ray-controller is updating the resource every a few seconds. 

<img width="1094" alt="Screenshot 2023-04-25 at 1 55 44 AM" src="https://user-images.githubusercontent.com/47722048/234108730-46083929-3b20-4d63-9cbc-f96810067e23.png">

The order of ports in the Head service keeps changing. 
```
  ports:
    - containerPort: 6379
      name: gcs-server
      protocol: TCP
    - containerPort: 8265
      name: dashboard
      protocol: TCP
    - containerPort: 10001
      name: client
      protocol: TCP
    - containerPort: 8000
      name: serve
      protocol: TCP
```

I also verified that `resourceVersion`  keeps updating every second.
```
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  creationTimestamp: '2023-04-24T11:28:58Z'
  generation: 1
  name: rayservice-sample
  namespace: ray-service-2
  resourceVersion: '12757119'
  uid: 8d8205ee-490b-6444-b14d-eb66bab2b84b
```

I believe this could be the possible cause  - https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/rayservice_controller.go#L112-L113

This leads to the concern of performance degradation of Kubernetes API server. This can also lead to performance degradation of ArgoCD, as every change in the resource will cause app to reconcile.

Is there any configuration on the RayController where this can be configured.

### Reproduction script

I installed the Kuberay operator on a test cluster. I am using ArgoCD for deploying RayService. All the resources ( head service, worker service, Ray Cluster etc)  are created on the test cluster.

1. Setup a test cluster or Reuse an existing cluster or Try locally on minikube.
2. Install the Kuberay operator on the cluster using this [link](https://github.com/ray-project/kuberay) 
3. Make sure that Test cluster is added on ArgoCD, If ArgoCD is not installed you will need to set this up.
4. Create a repository and add a sample RayService manifests.
5. Create an app in ArgoCD with the repo having RayService manifest.
6. ArgoCD should create the a bunch of resources and after a few minutes you should start seeing that pulsing animation.

Sample RayService manifest we used for testing
```
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: raycluster-autoscaler
  namespace: ray-sample
spec:
  rayVersion: '2.3.0'
  enableInTreeAutoscaling: true
  autoscalerOptions:
    upscalingMode: Default
    idleTimeoutSeconds: 60
    imagePullPolicy: IfNotPresent
    securityContext: {}
    env: []
    envFrom: []
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  # Ray head pod template
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.3.0
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          - containerPort: 8000
            name: serve
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "1"
              memory: "2G"
            requests:
              cpu: "500m"
              memory: "2G"
  workerGroupSpecs:
  - replicas: 1
    minReplicas: 1
    maxReplicas: 10
    groupName: small-group
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:2.3.0
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "500m"
              memory: "1G"
```

### Anything else

This is happening very frequently and there is no stop to it, Even after running it for for days.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment] 2023-04-24 20:58
> I believe this could be the possible cause - https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/rayservice_controller.go#L112-L113

In my opinion, this is not the root cause. KubeRay does not make any decision based on ObservedGeneration.

> Reproduction script

Which version of KubeRay do you use? This may be fixed in the master branch (the nightly Docker image) by https://github.com/ray-project/kuberay/pull/1014. Would you mind testing with the nightly Docker image? Thanks!

**Comment by msumitjain** [comment] 2023-04-24 21:22
Thanks for the response @kevin85421. 

We are using version 0.5.0. 
`kubectl create -k "github.com/ray-project/kuberay/ray-operator/config/default?ref=v0.5.0&timeout=90s"`

> This may be fixed in the master branch (the nightly Docker image) by https://github.com/ray-project/kuberay/pull/1014. Would you mind testing with the nightly Docker image?

Let me try one more time.

**Comment by msumitjain** [comment] 2023-04-26 09:46
Tried with nightly build and still the same behaviour.

**Comment by msumitjain** [comment] 2023-04-27 12:05
I observed that partial problem was with the way the ServicePorts are being created. Since a map is used to construct the ServicePorts List, the order of ports are always changing.

Instance 1 : 
 ```
   "ports": [
      {
        "name": "dashboard-agent",
        "appProtocol": "tcp",
        "port": 52365,
        "targetPort": 0
      },
      {
        "name": "metrics",
        "appProtocol": "tcp",
        "port": 8080,
        "targetPort": 0
      },
      {
        "name": "gcs-server",
        "appProtocol": "tcp",
        "port": 6379,
        "targetPort": 0
      },
      {
        "name": "dashboard",
        "appProtocol": "tcp",
        "port": 8265,
        "targetPort": 0
      },
      {
        "name": "client",
        "appProtocol": "tcp",
        "port": 10001,
        "targetPort": 0
      },
      {
        "name": "serve",
        "appProtocol": "tcp",
        "port": 8000,
        "targetPort": 0
      }
    ]
```

Instance 2 : 

```
 "ports": [
    {
      "name": "metrics",
      "appProtocol": "tcp",
      "port": 8080,
      "targetPort": 0
    },
    {
      "name": "gcs-server",
      "appProtocol": "tcp",
      "port": 6379,
      "targetPort": 0
    },
    {
      "name": "dashboard",
      "appProtocol": "tcp",
      "port": 8265,
      "targetPort": 0
    },
    {
      "name": "client",
      "appProtocol": "tcp",
      "port": 10001,
      "targetPort": 0
    },
    {
      "name": "serve",
      "appProtocol": "tcp",
      "port": 8000,
      "targetPort": 0
    },
    {
      "name": "dashboard-agent",
      "appProtocol": "tcp",
      "port": 52365,
      "targetPort": 0
    }
  ]
```

**Closed** 2023-05-02 07:22 UTC
Labels: bug
