### ISSUE TITLE
[Feature] multi-app support

### ISSUE THREAD

**Issue by v4if** [ray-project/kuberay#1142] opened 2023-06-06 09:40 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Is KubeRay support multi-app serve? such as the doc:
https://docs.ray.io/en/latest/serve/multi-app.html?highlight=serve%20multi#

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment] 2023-06-08 00:15
Thank @v4if for asking! @zcin is currently working on this feature, and multi-app is expected to be supported by KubeRay v0.6.0. This issue seems to be a duplicate of #985. Close this one.

**Closed by kevin85421** 2023-06-08 00:15 UTC
Labels: enhancement
